### ISSUE TITLE
Implement Redux

### ISSUE THREAD

**Issue by elliothimmelfarb** [elliothimmelfarb/truffle-split-it#36]

**Comment by kevinhealy** [comment]
Btw, just because I asked about it doesn't mean I think we should use redux for this app.

Only if it is necessary.

As far as I know, implementing this, at this point, would mean modifying most of the app.

**Comment by elliothimmelfarb** [comment]
It depends on how much more we want to do. Redux would make it simpler to maintain state across router view renders and keep state organized if we want to keep adding features and making improvements. Another option instead of Redux could be to just store all state in the root component and pass down and state getter and setter to all child components to simplify reading and modifying the application state. Again I think it depends on how much more we want to do. Adding Redux will make that future work simpler and more debuggable but the simpler implementation of state management could also work. Like I said yesterday we are just on the cusp of where adding full Redux makes sense but if there isn't much else we plan on adding/improving. Either implementation will require some relatively substantial reactors. The key here is we need to store much of the state that we are storing at the Create and View level at the App/root level

**Comment by elliothimmelfarb** [comment]
And have a clear and organized way of modifying and reading that state

**Comment by kevinhealy** [comment]
Ok, I'll leave the decision to you.  My primary concern is not how long it will take, but rather that we do what's right.

It's important to remember that everything we learn from making this (especially if we do it in a well crafted way) can be carried into future dapps as the "boilerplate".

So investing the time in doing it right now, is more important than getting it out the door.

Getting a half baked product out the door rarely ends well anyways.  (because it costs a lot of time and energy in customer support, band-aiding things that shouldn't have been there etc vs just spending the extra time in polish and doing it right the first time.)

**Comment by elliothimmelfarb** [comment]
Adding Redux is the right thing to do in this situation I think. It will also set us up for a solid boilerplate after stripping out all the split it specific code, like you said. It won't be too crazy of a refactor and things will make a lot more sense as far as logic and the location of state variables afterwards.

**Comment by kevinhealy** [comment]
Been learning redux.  Definitely think it's the right thing to do now.

**Comment by elliothimmelfarb** [comment]
Yeah React without Redux doesn't actually work very well once you get to moderate complexity. Good work learning! I'm hoping to get to work this weekend.
